### ISSUE TITLE
Panzoom library doesn't properly work an MacBook Pro (10.15.4)

### ISSUE THREAD

**Issue by BenjaminMaiwald** [KensingtonTech/ng2-panzoom#30] opened 2020-08-11 09:53 UTC
We use the panzoom library in an angular 9 project and encountered a problem with the panzoom library.
If this.panZoomConfig.panOnClickDrag is set to true, normal panning by clicking and dragging with the mouse works. A simple left mouse click without dragging however, leads to an endless loop where this.panZoomConfig.modelChanged keeps on firing events. The pan.x and pan.y, you get from subscribing to ModelChanged, attributes vary between -+infinity and NAN.
This leads to weird behaviour where it is no longer possible to drag and zooming either stops or doesn't correctly adjust itself.
The same behaviour occurs when using the official panzoom demo.
![PanzoomError on Macbook OS 10 15 4](https://user-images.githubusercontent.com/69507775/89883765-e7f8b600-dbc8-11ea-8eee-a71e50741e12.gif)
To simulate the error chrome and safari in the newest versions were used. Zoom into the image, leftclick multiple times. As seen in the video dragging is no longer possible and while zooming in and out, the image scrolls forward and backward on the same zoom level.

**Comment by KensingtonTech** [comment] 2020-08-11 22:12
Thank you for the report, @BenjaminMaiwald.  I believe I've located the issue, which is that there's occasionally a maths 'error' in the panVelocity calculation in the onMouseMove() handler, which interacts with the slow to halt animation.  As you saw, this occasionally renders the result as NaN or -Infinity.  This *should* be fixed now in version 9.0.1, by which I inserted a check which substitutes zero if it finds these invalid results, but the problem is admittedly not easy to reproduce.  Do please give it a go and report back whether it's resolved the problem for you.

PS. I was only able to reproduce the NaN, drag-to-click stops working behaviour.  I've not been able to reproduce the endless loop you reported, unless I misunderstood you.

**Comment by BenjaminMaiwald** [comment] 2020-08-12 07:18
Thank you, I'll try the new version and report back to you.

**Comment by BenjaminMaiwald** [comment] 2020-08-12 10:43
I just upgraded to version 9.0.1 and that fixed the issue. Thank you very much!

**Closed** 2020-08-12 12:40 UTC

**Comment by kd2801** [comment] 2020-08-17 04:51
Hi. I was facing similar issue. I updated to version 9.0.1. There is another issue which I am facing. When I am zooming in and zooming out using pinch wheel event, entire screen is zooming in/out instead of the panzoom elements.
